name : concatenation des indices

on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: generer indices.md
      run: |
        cat $(ls -v ${GITHUB_WORKSPACE}/indices/*.md) > ${GITHUB_WORKSPACE}/indices.md
    - name: Push
      run: |   
        git config --global user.name "bilalm78"
        git config --global user.email "mennitibilal8@gmail.com"
        git add indices.md
        git commit -m "Ajout du fichier contenant les indices fixes #15 "
        git push
